# Font
font_family      FiraCode Nerd Font
font_size        14.0

# Colors
include          ~/.config/kitty/themes/one-dark.conf

# Cursor
cursor_shape     block
cursor_blink     true

# Scrolling
scrollback_lines 10000

# Window title
active_tab_title_template  "{title}"
copy_on_select yes
tab_bar_edge top
editor nvim

# BEGIN_KITTY_THEME
# Adwaita darker
include current-theme.conf
# END_KITTY_THEME
shell zsh

map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+s paste_from_selectionmap 
ctrl+shift+enter new_window
map ctrl+shift+] next_window
map ctrl+shift+[ previous_window

enable_audio_bell no
